protocols: [udp, tcp]
rtspAddress: :8554
webrtc: yes
webrtcAddress: :8889
webrtcAdditionalHosts: [ "unfauceted-irene-contextually.ngrok-free.dev" ]

webrtcIceServers2:
  - url: stun:stun.l.google.com:19302

paths:
  # This will be the stream path, e.g., rtsp://<ip>:8554/cam
  cam:
    # Use the dedicated Raspberry Pi camera source
    source: rpiCamera
    sourceProtocol: tcp   # Forces the path to use TCP
    
    # Optional: Uncomment and change these to match your camera/needs
    rpiCameraWidth: 1024
    rpiCameraHeight: 768
    rpiCameraFPS: 30
    rpiCameraHFlip: true
    rpiCameraVFlip: true
    
    rpiCameraBitrate: 1000000
    rpiCameraAWB: 'auto'
    rpiCameraExposure: 'short'

  processed:
    sourceProtocol: tcp   # Forces the path to use TCP
